/**
 * FieldNotes — quick incident templates
 */
(function (global) {
  global.FieldNotesTemplates = [
    {
      id: "password-reset",
      label: "Password reset / account access",
      category: "Account",
      status: "Open",
      priority: "Normal",
      issue: "User cannot sign in / needs password or account access help.\n",
      checked: "Verified identity per policy.\nChecked account status in directory/admin console.\n",
      changed: "",
      result: "",
      followUp: "",
      tags: "account, access",
    },
    {
      id: "printer",
      label: "Printer issue",
      category: "Printer",
      status: "Open",
      priority: "Normal",
      issue: "Printing problem reported.\n",
      checked: "Checked printer online status and queue.\nChecked driver / default printer.\n",
      changed: "",
      result: "",
      followUp: "",
      tags: "printer",
    },
    {
      id: "wifi",
      label: "Wi-Fi / network issue",
      category: "Network",
      status: "Open",
      priority: "Normal",
      issue: "Network connectivity issue reported.\n",
      checked: "Checked Wi-Fi connection and IP configuration.\nChecked DHCP/DNS and gateway reachability.\n",
      changed: "",
      result: "",
      followUp: "",
      tags: "network, wifi",
    },
    {
      id: "m365",
      label: "Microsoft 365 / email issue",
      category: "Microsoft 365",
      status: "Open",
      priority: "Normal",
      issue: "Microsoft 365 or email issue reported.\n",
      checked: "Checked sign-in and licensing status.\nChecked mailbox / Outlook profile.\n",
      changed: "",
      result: "",
      followUp: "",
      tags: "m365, email",
    },
    {
      id: "phishing",
      label: "Suspicious email / phishing check",
      category: "Security",
      status: "Open",
      priority: "High",
      issue: "Suspicious email or link reported.\n",
      checked: "Reviewed headers and sender.\nChecked URL/reputation if applicable.\nAdvised user not to click further.\n",
      changed: "",
      result: "",
      followUp: "",
      tags: "security, email",
    },
    {
      id: "performance",
      label: "Device performance issue",
      category: "Hardware",
      status: "Open",
      priority: "Normal",
      issue: "Device slow or unresponsive.\n",
      checked: "Checked CPU/RAM/disk usage.\nChecked startup items and recent updates.\n",
      changed: "",
      result: "",
      followUp: "",
      tags: "performance",
    },
    {
      id: "software",
      label: "Software install / update",
      category: "Software",
      status: "Open",
      priority: "Normal",
      issue: "Software install or update requested.\n",
      checked: "Confirmed software name and version.\nChecked permissions and disk space.\n",
      changed: "",
      result: "",
      followUp: "",
      tags: "software",
    },
    {
      id: "3cx",
      label: "3CX / phone issue",
      category: "Phone/3CX",
      status: "Open",
      priority: "Normal",
      issue: "Phone / 3CX issue reported.\n",
      checked: "Checked extension registration and network.\nChecked headset/audio devices.\n",
      changed: "",
      result: "",
      followUp: "",
      tags: "3cx, phone",
    },
    {
      id: "datto",
      label: "Datto/RMM alert",
      category: "Datto/RMM",
      status: "Open",
      priority: "High",
      issue: "RMM/Datto alert received.\n",
      checked: "Reviewed alert details and affected device.\nChecked recent changes and current device status.\n",
      changed: "",
      result: "",
      followUp: "",
      tags: "datto, rmm, alert",
    },
    {
      id: "escalation",
      label: "Escalation note",
      category: "Other",
      status: "Escalated",
      priority: "High",
      issue: "Issue requires escalation.\n",
      checked: "Completed initial troubleshooting.\nDocumented findings for handover.\n",
      changed: "",
      result: "Escalated for further review.\n",
      followUp: "Awaiting response from escalated team.\n",
      tags: "escalation",
    },
    {
      id: "learning",
      label: "Learning / lab note",
      category: "Other",
      status: "Learning Note",
      priority: "Low",
      issue: "Learning objective / lab scenario.\n",
      checked: "Steps attempted and observations.\n",
      changed: "Changes made during lab.\n",
      result: "Outcome of exercise.\n",
      followUp: "Topics to revisit.\n",
      tags: "learning, lab",
    },
    {
      id: "general",
      label: "General troubleshooting",
      category: "Other",
      status: "Open",
      priority: "Normal",
      issue: "",
      checked: "",
      changed: "",
      result: "",
      followUp: "",
      tags: "",
    },
  ];
})(window);
